//! Minimal COM/WMI helpers for hardware telemetry.
//!
//! `windows-sys` 0.59 does not generate the Wbem* COM interfaces, so this
//! module hand-rolls the exact vtable slot layout of the four interfaces
//! WinKit reads from (IWbemLocator, IWbemServices, IEnumWbemClassObject,
//! IWbemClassObject). The layouts are fixed by the Windows SDK and have not
//! changed for supported Windows releases. Only the slots actually used are
//! ever called; the others are never invoked.
//!
//! Everything here is synchronous and bounded: each `WmiSession::query`
//! call creates and releases its own COM session on the calling thread, so a
//! stalled provider can never poison another thread's state.

use std::ffi::c_void;

use windows_sys::core::{BSTR, GUID, HRESULT};
use windows_sys::Win32::System::Com::{
    CoCreateInstance, CoInitializeEx, CLSCTX_INPROC_SERVER, COINIT_APARTMENTTHREADED,
    COINIT_MULTITHREADED,
};
use windows_sys::Win32::System::Variant::{VariantClear, VARIANT};

use crate::errors::{ErrorKind, WinkitError};
use crate::log_warn;
use crate::utils::wide_to_string;

/// HRESULT for `RPC_E_CHANGED_MODE` (0x80010106). Not generated by
/// windows-sys, so declared here.
pub const RPC_E_CHANGED_MODE: HRESULT = -2_147_417_850;

const CLSID_WBEM_LOCATOR: GUID = GUID::from_u128(0x4590f811_1d3a_11d0_891f_00aa004b2e24);
const IID_IWBEM_LOCATOR: GUID = GUID::from_u128(0xdc12a687_737f_11cf_884d_00aa004b2e24);

/// `WBEM_S_NO_ERROR` (0) and the end-of-enumeration sentinel `WBEM_S_FALSE`
/// (1) are the only success codes WMI queries use here.
const WBEM_S_NO_ERROR: HRESULT = 0;

// VT_UI4 / VT_I4 / VT_R8 / VT_BSTR / VT_BOOL / VT_EMPTY / VT_NULL / VT_UI8 / VT_I8 / VT_UI2 / VT_I2
const VT_UI4: u16 = 19;
const VT_I4: u16 = 3;
const VT_R8: u16 = 5;
const VT_BSTR: u16 = 8;
const VT_BOOL: u16 = 11;
const VT_EMPTY: u16 = 0;
const VT_NULL: u16 = 1;
const VT_UI8: u16 = 21;
const VT_I8: u16 = 20;
const VT_UI2: u16 = 18;
const VT_I2: u16 = 2;
const VT_UI1: u16 = 17;
const VT_I1: u16 = 16;

/// Read a vtable slot from a COM interface pointer. Every slot is one
/// function pointer (`usize`-sized).
unsafe fn slot(iface: *mut c_void, index: usize) -> usize {
    let vtbl = *(iface as *const *const usize);
    *vtbl.add(index)
}

/// Call `IUnknown::Release` (slot 2).
unsafe fn release(iface: *mut c_void) -> u32 {
    type F = unsafe extern "system" fn(*mut c_void) -> u32;
    std::mem::transmute::<usize, F>(slot(iface, 2))(iface)
}

type ConnectServerFn = unsafe extern "system" fn(
    *mut c_void,
    BSTR,
    BSTR,
    BSTR,
    BSTR,
    i32,
    BSTR,
    *mut c_void,
    *mut *mut c_void,
) -> HRESULT;
type ExecQueryFn = unsafe extern "system" fn(
    *mut c_void,
    BSTR,
    BSTR,
    i32,
    *mut c_void,
    *mut *mut c_void,
) -> HRESULT;
type NextFn =
    unsafe extern "system" fn(*mut c_void, i32, u32, *mut *mut c_void, *mut u32) -> HRESULT;

/// COM apartment initialization guard. Initializes COM for the calling
/// thread (MTA, falling back to STA) and uninitializes on drop.
struct ComGuard {
    initialized: bool,
}

impl ComGuard {
    fn new() -> Self {
        let mut initialized = false;
        unsafe {
            let hr = CoInitializeEx(std::ptr::null(), COINIT_MULTITHREADED as u32);
            if hr == 0 || hr == 1 {
                initialized = true;
            } else if hr == RPC_E_CHANGED_MODE {
                let hr2 = CoInitializeEx(std::ptr::null(), COINIT_APARTMENTTHREADED as u32);
                if hr2 == 0 || hr2 == 1 {
                    initialized = true;
                }
            } else {
                log_warn!("CoInitializeEx failed with hr={hr:#x}; WMI unavailable");
            }
        }
        Self { initialized }
    }
}

impl Drop for ComGuard {
    fn drop(&mut self) {
        if self.initialized {
            unsafe { windows_sys::Win32::System::Com::CoUninitialize() };
        }
    }
}

/// A typed wrapper over `IWbemLocator`.
struct WbemLocator(*mut c_void);

impl Drop for WbemLocator {
    fn drop(&mut self) {
        unsafe { release(self.0) };
    }
}

/// A typed wrapper over `IWbemServices`.
struct WbemServices(*mut c_void);

impl Drop for WbemServices {
    fn drop(&mut self) {
        unsafe { release(self.0) };
    }
}

/// A typed wrapper over `IEnumWbemClassObject`.
struct WbemEnum(*mut c_void);

impl Drop for WbemEnum {
    fn drop(&mut self) {
        unsafe { release(self.0) };
    }
}

/// A typed wrapper over `IWbemClassObject`.
struct WbemObject(*mut c_void);

impl Drop for WbemObject {
    fn drop(&mut self) {
        unsafe { release(self.0) };
    }
}

/// A simple, cloneable projection of a WMI property value. `VARIANT`s are
/// read into one of these immediately so the underlying COM object can be
/// released.
#[derive(Debug, Clone, PartialEq)]
pub enum WmiValue {
    U8(u8),
    U16(u16),
    U32(u32),
    U64(u64),
    I16(i16),
    I32(i32),
    I64(i64),
    F64(f64),
    Bool(bool),
    Str(String),
    /// Empty (VT_EMPTY) or null (VT_NULL) property value.
    Empty,
    /// A property WinKit does not decode; carried as text when available.
    Other(String),
}

impl WmiValue {
    pub fn as_u32(&self) -> Option<u32> {
        match self {
            Self::U32(v) => Some(*v),
            Self::U64(v) => u32::try_from(*v).ok(),
            Self::I32(v) => u32::try_from(*v).ok(),
            // Some providers (e.g. MSFT_PhysicalDisk in the storage stack)
            // return numeric properties as VT_BSTR strings.
            Self::Str(s) => s.parse::<u32>().ok(),
            _ => None,
        }
    }

    pub fn as_u64(&self) -> Option<u64> {
        match self {
            Self::U64(v) => Some(*v),
            Self::U32(v) => Some(*v as u64),
            Self::I64(v) => u64::try_from(*v).ok(),
            // WMI returns CIM uint64/sint64 properties (e.g.
            // Win32_PhysicalMemory.Capacity, Win32_DiskDrive.Size) as
            // VT_BSTR strings rather than numeric variants.
            Self::Str(s) => s.parse::<u64>().ok(),
            _ => None,
        }
    }

    pub fn as_u16(&self) -> Option<u16> {
        match self {
            Self::U16(v) => Some(*v),
            Self::U32(v) => u16::try_from(*v).ok(),
            _ => None,
        }
    }

    pub fn as_f64(&self) -> Option<f64> {
        match self {
            Self::F64(v) => Some(*v),
            Self::U32(v) => Some(*v as f64),
            Self::U64(v) => Some(*v as f64),
            Self::I32(v) => Some(*v as f64),
            Self::I64(v) => Some(*v as f64),
            Self::U16(v) => Some(*v as f64),
            Self::I16(v) => Some(*v as f64),
            _ => None,
        }
    }

    pub fn as_string(&self) -> Option<String> {
        match self {
            Self::Str(s) => Some(s.clone()),
            Self::U32(v) => Some(v.to_string()),
            Self::U64(v) => Some(v.to_string()),
            Self::I32(v) => Some(v.to_string()),
            Self::I64(v) => Some(v.to_string()),
            Self::F64(v) => Some(v.to_string()),
            _ => None,
        }
    }
}

fn variant_to_value(v: &VARIANT) -> WmiValue {
    unsafe {
        let vt = v.Anonymous.Anonymous.vt;
        let inner = &v.Anonymous.Anonymous.Anonymous;
        match vt {
            VT_EMPTY | VT_NULL => WmiValue::Empty,
            VT_UI1 => WmiValue::U8(inner.bVal),
            VT_I1 => WmiValue::U8(inner.cVal as u8),
            VT_UI2 => WmiValue::U16(inner.uiVal),
            VT_I2 => WmiValue::I16(inner.iVal),
            VT_UI4 => WmiValue::U32(inner.ulVal),
            VT_I4 => WmiValue::I32(inner.lVal),
            VT_UI8 => WmiValue::U64(inner.ullVal),
            VT_I8 => WmiValue::I64(inner.llVal),
            VT_R8 => WmiValue::F64(inner.dblVal),
            VT_BOOL => WmiValue::Bool(inner.boolVal != 0),
            VT_BSTR => {
                if inner.bstrVal.is_null() {
                    WmiValue::Empty
                } else {
                    let len = crate::platform::windows::ffi::bstr_len(inner.bstrVal);
                    WmiValue::Str(wide_to_string(std::slice::from_raw_parts(
                        inner.bstrVal,
                        len,
                    )))
                }
            }
            other => WmiValue::Other(format!("vt=0x{other:x}")),
        }
    }
}

/// One WMI instance with its decoded properties.
#[derive(Debug, Clone, Default)]
pub struct WmiObject {
    pub properties: Vec<(String, WmiValue)>,
}

impl WmiObject {
    pub fn get(&self, name: &str) -> Option<&WmiValue> {
        self.properties
            .iter()
            .find(|(k, _)| k.eq_ignore_ascii_case(name))
            .map(|(_, v)| v)
    }

    pub fn get_u32(&self, name: &str) -> Option<u32> {
        self.get(name).and_then(WmiValue::as_u32)
    }

    pub fn get_f64(&self, name: &str) -> Option<f64> {
        self.get(name).and_then(WmiValue::as_f64)
    }

    pub fn get_string(&self, name: &str) -> Option<String> {
        self.get(name).and_then(WmiValue::as_string)
    }

    /// The `__PATH` of the instance, e.g.
    /// `\\host\root\WMI:MSAcpi_ThermalZoneTemperature.InstanceName="0"`.
    pub fn path(&self) -> Option<String> {
        self.get_string("__PATH")
    }

    /// The `InstanceName` key of the instance when `__PATH` carries one.
    pub fn instance_name(&self) -> Option<String> {
        let path = self.path()?;
        let idx = path.find("InstanceName=\"")?;
        let rest = &path[idx + "InstanceName=\"".len()..];
        let end = rest.find('"')?;
        Some(rest[..end].to_string())
    }
}

/// A bound WMI session on one namespace.
///
/// `services` is deliberately declared before `_com`: Rust drops struct
/// fields in declaration order, so the WMI proxy must be released while the
/// COM apartment is still initialized. Dropping `_com` first would run
/// `CoUninitialize` and then `Release` a proxy whose apartment is gone —
/// an access violation.
pub struct WmiSession {
    services: WbemServices,
    _com: ComGuard,
}

impl WmiSession {
    /// Connect to a WMI namespace such as `root\\cimv2` or `root\\WMI`.
    pub fn connect(namespace: &str) -> Result<Self, WinkitError> {
        let com = ComGuard::new();
        if !com.initialized {
            return Err(WinkitError::new(
                ErrorKind::WindowsApiError,
                format!("cannot initialize COM for WMI namespace '{namespace}'"),
            ));
        }
        unsafe {
            let mut locator: *mut c_void = std::ptr::null_mut();
            let hr = CoCreateInstance(
                &CLSID_WBEM_LOCATOR,
                std::ptr::null_mut(),
                CLSCTX_INPROC_SERVER,
                &IID_IWBEM_LOCATOR,
                &mut locator,
            );
            if hr < 0 || locator.is_null() {
                return Err(WinkitError::new(
                    ErrorKind::WindowsApiError,
                    format!("CoCreateInstance(WbemLocator) failed with hr={hr:#x}"),
                ));
            }
            let locator = WbemLocator(locator);

            let ns = to_bstr(namespace);
            let mut services: *mut c_void = std::ptr::null_mut();
            let hr = {
                type F = ConnectServerFn;
                let f: F = std::mem::transmute::<usize, F>(slot(locator.0, 3));
                f(
                    locator.0,
                    ns,
                    std::ptr::null(),
                    std::ptr::null(),
                    std::ptr::null(),
                    0,
                    std::ptr::null(),
                    std::ptr::null_mut(),
                    &mut services,
                )
            };
            free_bstr(ns);
            if hr < 0 || services.is_null() {
                return Err(WinkitError::new(
                    ErrorKind::WindowsApiError,
                    format!("IWbemLocator::ConnectServer('{namespace}') failed with hr={hr:#x}"),
                ));
            }
            // WMI proxies need explicit security settings before any query:
            // without a blanket, `IWbemServices::ExecQuery` returns
            // `WBEM_E_ACCESS_DENIED` even for a non-elevated user.
            let blanket = {
                use windows_sys::Win32::System::Com::{
                    CoSetProxyBlanket, RPC_C_AUTHN_LEVEL_PKT_PRIVACY,
                };
                // `RPC_C_AUTHN_WINNT`, `RPC_C_AUTHZ_NONE`, and `EOAC_NONE`
                // are not generated because the `Win32_System_Rpc` feature
                // is not enabled; they are fixed SDK values.
                const RPC_C_AUTHN_WINNT: u32 = 10;
                const RPC_C_AUTHZ_NONE: u32 = 0;
                const RPC_C_IMP_LEVEL_IMPERSONATE: u32 = 3;
                const EOAC_NONE: u32 = 0;
                CoSetProxyBlanket(
                    services,
                    RPC_C_AUTHN_WINNT,
                    RPC_C_AUTHZ_NONE,
                    std::ptr::null(),
                    RPC_C_AUTHN_LEVEL_PKT_PRIVACY,
                    RPC_C_IMP_LEVEL_IMPERSONATE,
                    std::ptr::null(),
                    EOAC_NONE,
                )
            };
            if blanket < 0 {
                return Err(WinkitError::new(
                    ErrorKind::WindowsApiError,
                    format!("CoSetProxyBlanket(WbemServices) failed with hr={blanket:#x}"),
                ));
            }
            Ok(Self {
                services: WbemServices(services),
                _com: com,
            })
        }
    }

    /// Run a WQL query and collect every returned instance.
    pub fn query(&self, wql: &str) -> Result<Vec<WmiObject>, WinkitError> {
        unsafe {
            let ql = to_bstr("WQL");
            let q = to_bstr(wql);
            let mut enumerator: *mut c_void = std::ptr::null_mut();
            let hr = {
                type F = ExecQueryFn;
                let f: F = std::mem::transmute::<usize, F>(slot(self.services.0, 20));
                f(
                    self.services.0,
                    ql,
                    q,
                    0,
                    std::ptr::null_mut(),
                    &mut enumerator,
                )
            };
            free_bstr(ql);
            free_bstr(q);
            if hr < 0 || enumerator.is_null() {
                return Err(WinkitError::new(
                    ErrorKind::WindowsApiError,
                    format!("IWbemServices::ExecQuery failed with hr={hr:#x}"),
                ));
            }
            let enumerator = WbemEnum(enumerator);

            let mut objects = Vec::new();
            loop {
                let mut raw: *mut c_void = std::ptr::null_mut();
                let mut returned: u32 = 0;
                let hr = {
                    type F = NextFn;
                    let f: F = std::mem::transmute::<usize, F>(slot(enumerator.0, 4));
                    f(enumerator.0, 0, 1, &mut raw, &mut returned)
                };
                if hr != WBEM_S_NO_ERROR || returned == 0 || raw.is_null() {
                    break;
                }
                let obj = WbemObject(raw);
                objects.push(read_object(&obj));
            }
            Ok(objects)
        }
    }
}

/// Read every property of a `IWbemClassObject` instance. This is bounded:
/// the SDK fixes the maximum property count WinKit cares about, and WMI
/// property names are short.
fn read_object(obj: &WbemObject) -> WmiObject {
    unsafe {
        // `IWbemClassObject::BeginEnumeration` is vtable slot 8; it accepts
        // the flags (0 = all properties) and resets the cursor.
        type BeginFn = unsafe extern "system" fn(*mut c_void, i32) -> HRESULT;
        let begin: BeginFn = std::mem::transmute::<usize, BeginFn>(slot(obj.0, 8));
        if begin(obj.0, 0) < 0 {
            return WmiObject::default();
        }

        // `IWbemClassObject::Next` is vtable slot 9.
        type NextPropFn = unsafe extern "system" fn(
            *mut c_void,
            i32,
            *mut BSTR,
            *mut VARIANT,
            *mut i32,
            *mut i32,
        ) -> HRESULT;
        let next: NextPropFn = std::mem::transmute::<usize, NextPropFn>(slot(obj.0, 9));

        let mut out = WmiObject::default();
        loop {
            let mut name: BSTR = std::ptr::null();
            let mut value: VARIANT = std::mem::zeroed();
            let mut cim_type: i32 = 0;
            let mut flavor: i32 = 0;
            let hr = next(obj.0, 0, &mut name, &mut value, &mut cim_type, &mut flavor);
            if hr != WBEM_S_NO_ERROR || name.is_null() {
                break;
            }
            let name_str = {
                let len = crate::platform::windows::ffi::bstr_len(name);
                wide_to_string(std::slice::from_raw_parts(name, len))
            };
            let decoded = variant_to_value(&value);
            VariantClear(&mut value);
            crate::platform::windows::ffi::free_bstr_raw(name);
            out.properties.push((name_str, decoded));
        }

        // `IWbemClassObject::EndEnumeration` is vtable slot 10.
        type EndFn = unsafe extern "system" fn(*mut c_void) -> HRESULT;
        let end: EndFn = std::mem::transmute::<usize, EndFn>(slot(obj.0, 10));
        end(obj.0);
        out
    }
}

/// Allocate a `BSTR` from a string via oleaut32 (`SysAllocString`). The
/// caller must free it with [`free_bstr`].
///
/// # Safety
///
/// The returned `BSTR` must be freed exactly once with [`free_bstr`] (or
/// `SysFreeString`); it is never garbage-collected.
pub unsafe fn to_bstr(s: &str) -> BSTR {
    crate::platform::windows::ffi::to_bstr(s)
}

/// Free a `BSTR` allocated by WinKit.
///
/// # Safety
///
/// `b` must be a `BSTR` allocated by [`to_bstr`] or `SysAllocString`, and it
/// must not have been freed already.
pub unsafe fn free_bstr(b: BSTR) {
    crate::platform::windows::ffi::free_bstr_raw(b)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn as_u64_reads_numeric_strings_wmi_uint64_style() {
        // WMI returns CIM uint64 properties (Capacity, Size) as VT_BSTR.
        let v = WmiValue::Str("512105932800".into());
        assert_eq!(v.as_u64(), Some(512_105_932_800));
        assert_eq!(WmiValue::U64(42).as_u64(), Some(42));
        assert_eq!(WmiValue::U32(7).as_u64(), Some(7));
        assert_eq!(WmiValue::Str("not-a-number".into()).as_u64(), None);
        assert_eq!(WmiValue::Empty.as_u64(), None);
    }

    #[test]
    fn as_u32_reads_numeric_strings_storage_stack_style() {
        // The storage stack returns DeviceId as VT_BSTR.
        let v = WmiValue::Str("0".into());
        assert_eq!(v.as_u32(), Some(0));
        assert_eq!(WmiValue::I32(11).as_u32(), Some(11));
        assert_eq!(WmiValue::Str("not-a-number".into()).as_u32(), None);
    }
}
